project:
  type: website
  output-dir: docs

website:
  title: "Meerkating Around"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Nika_Self.qmd
        text: Nika Self
      - href: Fun_Facts.qmd
        text: Fun Facts
      - href: Find_A_Meerkat_Near_You.qmd
        text: Find A Meerkat Near You
      - href: Find_A_Meerkat_In_The_Wild.qmd
        text: Find A Meerkat In The Wild  

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true



